# Generated by Django 5.2.7 on 2025-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='partner_id',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='product_id',
            new_name='product',
        ),
    ]
