# Generated by Django 5.2.7 on 2025-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ordered_quantity',
            field=models.IntegerField(default=True),
        ),
    ]
